#!/usr/bin/ruby

file_name = ARGV.first
raise "no filename given!" if file_name.nil?
raise "file #{ file_name } already exists!" if File.exists?(file_name)


File.open(file_name, 'a') do | file |
  file.write("#!/usr/bin/ruby\n")
end

`chmod u+x #{ file_name }`

